export CFLAGS=-I/opt/xbmc-ce41xx/local/include -I/opt/xbmc-ce41xx/IntelCE/include -I/opt/xbmc-ce41xx/IntelCE/usr/include -I/opt/xbmc-ce41xx/IntelCE/usr/local/include
export CXXFLAGS=${CFLAGS}
export CPPFLAGS=${CFLAGS}
export LIBS=-L/opt/xbmc-ce41xx/local/lib -L/opt/xbmc-ce41xx/IntelCE/lib -L/opt/xbmc-ce41xx/IntelCE/usr/lib
export LDFLAGS=-L/opt/xbmc-ce41xx/local/lib -L/opt/xbmc-ce41xx/IntelCE/lib -L/opt/xbmc-ce41xx/IntelCE/usr/lib
export CROSSBIN=/opt/xbmc-ce41xx/toolchains/i686-cm-linux-
export CC=${CROSSBIN}gcc
export CXX=${CROSSBIN}g++
export LD=${CROSSBIN}ld
export AR=${CROSSBIN}ar
export RANLIB=${CROSSBIN}ranlib
export STRIP=${CROSSBIN}strip
export OBJDUMP=${CROSSBIN}objdump 
export PREFIX=/opt/xbmc-ce41xx/local
export HOST=i686-cm-linux
export BUILD=i686-linux
export CXXCPP=${CXX} -E
export PKG_CONFIG_LIBDIR=/opt/xbmc-ce41xx/local/lib/pkgconfig
export TARGETFS=/opt/xbmc-ce41xx/targetfs
export PATH:=/opt/xbmc-ce41xx/toolchains:$(PATH)
