export PREFIX=${XBMCPREFIX}
export CFLAGS=-isystem${XBMCPREFIX}/include -isystem${SDKSTAGE}/include -isystem${SDKSTAGE}/usr/include -mfpmath=sse -msse3 -O3
export CXXFLAGS=${CFLAGS}
export CPPFLAGS=${CFLAGS}
export LDFLAGS=-L${PREFIX}/lib -L${SDKSTAGE}/lib -L${SDKSTAGE}/usr/lib
export CROSSBIN=${TOOLCHAIN}/i686-cm-linux-
export CC=${CROSSBIN}gcc
export CXX=${CROSSBIN}g++
export LD=${CROSSBIN}ld
export AR=${CROSSBIN}ar
export RANLIB=${CROSSBIN}ranlib
export STRIP=${CROSSBIN}strip
export OBJDUMP=${CROSSBIN}objdump 
export ACLOCAL=aclocal -I ${PREFIX}/share/aclocal -I ${PREFIX}/share/aclocal-1.10 -I ${SDKSTAGE}/share/aclocal
export HOST=i686-cm-linux
export BUILD=i686-linux
export CXXCPP=${CXX} -E
export PKG_CONFIG_LIBDIR=${PREFIX}/lib/pkgconfig:${SDKSTAGE}/lib/pkgconfig:${SDKSTAGE}/usr/lib/pkgconfig
export TARGETFS=${BUILDROOT}/project_build_i686/IntelCE/root/
export PATH:=${PREFIX}/bin:${TOOLCHAIN}:$(PATH)
