INCLUDES=-I. -I../ -I../../ -I../../../ -I../../FileSystem -I../../linux -I../../cores -I../../../lib/cpluff/ -I../../../lib

SRCS=HttpApi.cpp XBMChttp.cpp

LIB=http-api.a

include ../../../Makefile.include

