INCLUDES=-I. -I../ -I../../ -I../../../ -I../../FileSystem -I../../linux -I../../cores -I../../../lib/jsoncpp/jsoncpp/include -I../../../lib

SRCS=JSONRPC.cpp PlayerOperations.cpp AVPlayerOperations.cpp PicturePlayerOperations.cpp AVPlaylistOperations.cpp PlaylistOperations.cpp FileOperations.cpp AudioLibrary.cpp VideoLibrary.cpp FileItemHandler.cpp SystemOperations.cpp XBMCOperations.cpp

LIB=json-rpc.a

include ../../../Makefile.include

